### ISSUE TITLE
document creation of adapter-and-janus.js

### ISSUE THREAD

**Issue by rbray89** [jurriaan/janus-stream-custom-component#2]
In trying to improve long-running stream stability, I'm attempting to update any potential points of issues to more recent versions. One of these items is the adapter-and-janus.js source material, as it seems like it *may* be somewhat dated.

**Comment by jurriaan** [comment]
Added a very basic script to update the file. See `script/update-3rdparty-js`.

To further improve long-running stream ability you probably need to act on certain events to restart the stream in `custom_components/janus_stream/www/janus-camera.js`
